name: Actions workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - id: greet
      - name: Simple JS Action
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Icon
      - name: Log Greeting Time
        run: echo "${{steps.greet.output.time}}"
